### ISSUE TITLE
FreeBSD could be a thing too...

### ISSUE THREAD

**Issue by robertu94** [CUCyber/hackpack#49]
We should also probably set up a freeBSD machine for testing also, so that we have a rough idea of how to use it.

**Comment by robertu94** [comment]
It would probably be helpful to have a hardcopy of the FreeBSD handbook https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/book.html

**Comment by mdclyburn** [comment]
I see this has been sitting here for a while. Pulling information from the handbook is easy. Any specific information you want? I can help.
