### ISSUE TITLE
HackPack PDF missing from website

### ISSUE THREAD

**Issue by mbinns** [CUCyber/hackpack#74]
The page returns a 404 when the pdf link is clicked

**Comment by klsimps** [comment]
The hackpack was deleted somehow. I added it back and everything is good now.

**Comment by klsimps** [comment]
This is resolved.

**Comment by lilyinstarlight** [comment]
I forgot to update the link in the description. It is located at https://cucyber.net/documents/hackpack.pdf now. I'll fix this right now.
