### ISSUE TITLE
Linux Competition Starting Checklists

### ISSUE THREAD

**Issue by nbulischeck** [CUCyber/hackpack#85]
1. Should we remove the "Download toolset" section?
2. Should we remove the "Limit cron to root" section?
3. Should we add `rm -rf /etc/cron*` under the cron section?
4. Should we add box-specific sections? I.e. CentOS Ecom, Ubuntu DNS/SSH, etc.
5. Should we add `grep "/bin.*sh" /etc/passwd` under "Audit users and groups for invalid entries"?

Hackpack as a whole:
1. Should we add a `Lokkit` section?
2. Should we add a section for repairing expired repos?

**Comment by westonbelk** [comment]
Hackpack as a whole
1. Yes
2. We have #7 for fixing RPM-based distros, but not an issue for other distros.

**Comment by lilyinstarlight** [comment]
1. Yes
2. Just change it to disable cron
3. No
4. Yeah, we can add and remove those as needed per competition. We've done that before iirc.
5. Yeah, that could be useful but I'd like it more general if possible, i.e. `grep -v /bin/bash | grep -v /bin/sh | grep -v /bin/nologin | grep -v /bin/false`.

**Comment by westonbelk** [comment]
Checklist has been revised since this issue was relevant.
